import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;


public class ManageViewLeave extends javax.swing.JFrame {
    
    private List<LeaveRecord> leaveRecords = new ArrayList<>();
    /**
     * Creates new form ManageViewLeave
     */
    public ManageViewLeave() {
        initComponents();
        readLeaveData();
        displayLeaveRecords();
    }

        private void readLeaveData() {
        String filePath = "LeaveManagement\\\\LeaveApplication.txt";

        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;
            LeaveRecord currentRecord = null;
            
            while ((line = br.readLine()) != null) {
                if (line.startsWith("NRIC :")) {
                    if (currentRecord != null) {
                        leaveRecords.add(currentRecord);
                    }
                    currentRecord = new LeaveRecord();
                    line.substring("NRIC :".length()).trim();
                } else if (line.startsWith("Start Date:")) {
                    if (currentRecord != null) {
                        currentRecord.startDate = line.substring("Start Date:".length()).trim();
                    }
                } else if (line.startsWith("End Date:")) {
                    if (currentRecord != null) {
                        currentRecord.endDate = line.substring("End Date:".length()).trim();
                    }
                }
                // Ignore other fields
            }
            
            // Add the last record if available
            if (currentRecord != null) {
                leaveRecords.add(currentRecord);
            }
            
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error reading the file: " + e.getMessage(), "File Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void displayLeaveRecords() {
        if (leaveRecords.size() > 0) {
            LeaveRecord firstRecord = leaveRecords.get(0);
            StartDatetxt.setText("Start Date: " + firstRecord.startDate);
            EndDatetxt.setText("End Date: " + firstRecord.endDate);
        } else {
            StartDatetxt.setText("Start Date: ");
            EndDatetxt.setText("End Date: ");
        }
        if (leaveRecords.size() > 1) {
            LeaveRecord secondRecord = leaveRecords.get(1);
            StartDatetxt1.setText("Start Date: " + secondRecord.startDate);
            EndDatetxt1.setText("End Date: " + secondRecord.endDate);
        } else {
            StartDatetxt1.setText("Start Date: ");
            EndDatetxt1.setText("End Date: ");
        }
        if (leaveRecords.size() > 2) {
            LeaveRecord thirdRecord = leaveRecords.get(2);
            StartDatetxt2.setText("Start Date: " + thirdRecord.startDate);
            EndDatetxt2.setText("End Date: " + thirdRecord.endDate);
        } else {
            StartDatetxt2.setText("Start Date: ");
            EndDatetxt2.setText("End Date: ");
        }
        if (leaveRecords.size() > 3) {
            LeaveRecord fourthRecord = leaveRecords.get(3);
            StartDatetxt3.setText("Start Date: " + fourthRecord.startDate);
            EndDatetxt3.setText("End Date: " + fourthRecord.endDate);
        } else {
            StartDatetxt3.setText("Start Date: ");
            EndDatetxt3.setText("End Date: ");
        }
        if (leaveRecords.size() > 4) {
            LeaveRecord fifthRecord = leaveRecords.get(4);
            StartDatetxt4.setText("Start Date: " + fifthRecord.startDate);
            EndDatetxt4.setText("End Date: " + fifthRecord.endDate);
        } else {
            StartDatetxt4.setText("Start Date: ");
            EndDatetxt4.setText("End Date: ");
        }
        if (leaveRecords.size() > 5) {
            LeaveRecord sixthRecord = leaveRecords.get(5);
            StartDatetxt5.setText("Start Date: " + sixthRecord.startDate);
            EndDatetxt5.setText("End Date: " + sixthRecord.endDate);
        } else {
            StartDatetxt5.setText("Start Date: ");
            EndDatetxt5.setText("End Date: ");
        }
    }
    
    private class LeaveRecord {
        String startDate;
        String endDate;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Leave1 = new javax.swing.JPanel();
        Datetxt = new javax.swing.JLabel();
        EndDatetxt = new javax.swing.JLabel();
        StartDatetxt = new javax.swing.JLabel();
        Untiltxt = new javax.swing.JLabel();
        Checkbtn1 = new javax.swing.JButton();
        Leave2 = new javax.swing.JPanel();
        Datetxt1 = new javax.swing.JLabel();
        EndDatetxt1 = new javax.swing.JLabel();
        StartDatetxt1 = new javax.swing.JLabel();
        Untiltxt1 = new javax.swing.JLabel();
        Checkbtn2 = new javax.swing.JButton();
        Leave3 = new javax.swing.JPanel();
        Datetxt2 = new javax.swing.JLabel();
        EndDatetxt2 = new javax.swing.JLabel();
        StartDatetxt2 = new javax.swing.JLabel();
        Untiltxt2 = new javax.swing.JLabel();
        Checkbtn3 = new javax.swing.JButton();
        Leave4 = new javax.swing.JPanel();
        Datetxt3 = new javax.swing.JLabel();
        EndDatetxt3 = new javax.swing.JLabel();
        StartDatetxt3 = new javax.swing.JLabel();
        Untiltxt3 = new javax.swing.JLabel();
        Checkbtn4 = new javax.swing.JButton();
        Leave5 = new javax.swing.JPanel();
        Datetxt4 = new javax.swing.JLabel();
        EndDatetxt4 = new javax.swing.JLabel();
        StartDatetxt4 = new javax.swing.JLabel();
        Untiltxt4 = new javax.swing.JLabel();
        Checkbtn5 = new javax.swing.JButton();
        Leave6 = new javax.swing.JPanel();
        Datetxt5 = new javax.swing.JLabel();
        EndDatetxt5 = new javax.swing.JLabel();
        StartDatetxt5 = new javax.swing.JLabel();
        Untiltxt5 = new javax.swing.JLabel();
        Checkbtn6 = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manager View Leave", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        Leave1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Datetxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Datetxt.setText("Date: ");

        Untiltxt.setText("---");

        Checkbtn1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Checkbtn1.setText("Check");
        Checkbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Checkbtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Leave1Layout = new javax.swing.GroupLayout(Leave1);
        Leave1.setLayout(Leave1Layout);
        Leave1Layout.setHorizontalGroup(
            Leave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Datetxt)
                .addGap(55, 55, 55)
                .addComponent(StartDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Untiltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EndDatetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(Checkbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Leave1Layout.setVerticalGroup(
            Leave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Leave1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Checkbtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Untiltxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(EndDatetxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Datetxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StartDatetxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Leave2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Datetxt1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Datetxt1.setText("Date: ");

        Untiltxt1.setText("---");

        Checkbtn2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Checkbtn2.setText("Check");
        Checkbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Checkbtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Leave2Layout = new javax.swing.GroupLayout(Leave2);
        Leave2.setLayout(Leave2Layout);
        Leave2Layout.setHorizontalGroup(
            Leave2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Datetxt1)
                .addGap(55, 55, 55)
                .addComponent(StartDatetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Untiltxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EndDatetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Checkbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Leave2Layout.setVerticalGroup(
            Leave2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Leave2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Checkbtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Untiltxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(EndDatetxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Datetxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StartDatetxt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Leave3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Datetxt2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Datetxt2.setText("Date: ");

        Untiltxt2.setText("---");

        Checkbtn3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Checkbtn3.setText("Check");
        Checkbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Checkbtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Leave3Layout = new javax.swing.GroupLayout(Leave3);
        Leave3.setLayout(Leave3Layout);
        Leave3Layout.setHorizontalGroup(
            Leave3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Datetxt2)
                .addGap(55, 55, 55)
                .addComponent(StartDatetxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Untiltxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EndDatetxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Checkbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Leave3Layout.setVerticalGroup(
            Leave3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Leave3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Checkbtn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Untiltxt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(EndDatetxt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Datetxt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StartDatetxt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Leave4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Datetxt3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Datetxt3.setText("Date: ");

        Untiltxt3.setText("---");

        Checkbtn4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Checkbtn4.setText("Check");
        Checkbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Checkbtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Leave4Layout = new javax.swing.GroupLayout(Leave4);
        Leave4.setLayout(Leave4Layout);
        Leave4Layout.setHorizontalGroup(
            Leave4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Datetxt3)
                .addGap(55, 55, 55)
                .addComponent(StartDatetxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Untiltxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EndDatetxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Checkbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Leave4Layout.setVerticalGroup(
            Leave4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Leave4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Checkbtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Untiltxt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(EndDatetxt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Datetxt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StartDatetxt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Leave5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Datetxt4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Datetxt4.setText("Date: ");

        Untiltxt4.setText("---");

        Checkbtn5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Checkbtn5.setText("Check");
        Checkbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Checkbtn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Leave5Layout = new javax.swing.GroupLayout(Leave5);
        Leave5.setLayout(Leave5Layout);
        Leave5Layout.setHorizontalGroup(
            Leave5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Datetxt4)
                .addGap(55, 55, 55)
                .addComponent(StartDatetxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Untiltxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EndDatetxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Checkbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Leave5Layout.setVerticalGroup(
            Leave5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Leave5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Checkbtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Untiltxt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(EndDatetxt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Datetxt4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StartDatetxt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Leave6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Datetxt5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Datetxt5.setText("Date: ");

        Untiltxt5.setText("---");

        Checkbtn6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Checkbtn6.setText("Check");
        Checkbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Checkbtn6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Leave6Layout = new javax.swing.GroupLayout(Leave6);
        Leave6.setLayout(Leave6Layout);
        Leave6Layout.setHorizontalGroup(
            Leave6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Datetxt5)
                .addGap(55, 55, 55)
                .addComponent(StartDatetxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Untiltxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EndDatetxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Checkbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        Leave6Layout.setVerticalGroup(
            Leave6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Leave6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Leave6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Checkbtn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Untiltxt5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(EndDatetxt5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Datetxt5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(StartDatetxt5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Backbtn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Leave1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Leave2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Leave3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Leave4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Leave5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Leave6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Leave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Leave2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Leave3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Leave4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Leave5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Leave6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(Backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void Checkbtn1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (!leaveRecords.isEmpty()) {
            int recordIndex = 0;
            ManageStatus managestatus = new ManageStatus (recordIndex);
            managestatus.setVisible(true);
            this.dispose();
        }
    }                                         
   
    
    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        ManagerMenu managermenu = new ManagerMenu();
        managermenu.setVisible(true);

        this.dispose();
    }                                       

    private void Checkbtn2ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (!leaveRecords.isEmpty()) {
            int recordIndex = 1;
            ManageStatus managestatus = new ManageStatus (recordIndex);
            managestatus.setVisible(true);
            this.dispose();
        }
    }                                         

    private void Checkbtn3ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (!leaveRecords.isEmpty()) {
            int recordIndex = 2;
            ManageStatus managestatus = new ManageStatus (recordIndex);
            managestatus.setVisible(true);
            this.dispose();
        }
    }                                         

    private void Checkbtn4ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (!leaveRecords.isEmpty()) {
            int recordIndex = 3;
            ManageStatus managestatus = new ManageStatus (recordIndex);
            managestatus.setVisible(true);
            this.dispose();
        }
    }                                         

    private void Checkbtn5ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (!leaveRecords.isEmpty()) {
            int recordIndex = 4;
            ManageStatus managestatus = new ManageStatus (recordIndex);
            managestatus.setVisible(true);
            this.dispose();
        }
    }                                         

    private void Checkbtn6ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if (!leaveRecords.isEmpty()) {
            int recordIndex = 5;
            ManageStatus managestatus = new ManageStatus (recordIndex);
            managestatus.setVisible(true);
            this.dispose();
        }
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageViewLeave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageViewLeave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageViewLeave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageViewLeave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageViewLeave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton Checkbtn1;
    private javax.swing.JButton Checkbtn2;
    private javax.swing.JButton Checkbtn3;
    private javax.swing.JButton Checkbtn4;
    private javax.swing.JButton Checkbtn5;
    private javax.swing.JButton Checkbtn6;
    private javax.swing.JLabel Datetxt;
    private javax.swing.JLabel Datetxt1;
    private javax.swing.JLabel Datetxt2;
    private javax.swing.JLabel Datetxt3;
    private javax.swing.JLabel Datetxt4;
    private javax.swing.JLabel Datetxt5;
    private javax.swing.JLabel EndDatetxt;
    private javax.swing.JLabel EndDatetxt1;
    private javax.swing.JLabel EndDatetxt2;
    private javax.swing.JLabel EndDatetxt3;
    private javax.swing.JLabel EndDatetxt4;
    private javax.swing.JLabel EndDatetxt5;
    private javax.swing.JPanel Leave1;
    private javax.swing.JPanel Leave2;
    private javax.swing.JPanel Leave3;
    private javax.swing.JPanel Leave4;
    private javax.swing.JPanel Leave5;
    private javax.swing.JPanel Leave6;
    private javax.swing.JLabel StartDatetxt;
    private javax.swing.JLabel StartDatetxt1;
    private javax.swing.JLabel StartDatetxt2;
    private javax.swing.JLabel StartDatetxt3;
    private javax.swing.JLabel StartDatetxt4;
    private javax.swing.JLabel StartDatetxt5;
    private javax.swing.JLabel Untiltxt;
    private javax.swing.JLabel Untiltxt1;
    private javax.swing.JLabel Untiltxt2;
    private javax.swing.JLabel Untiltxt3;
    private javax.swing.JLabel Untiltxt4;
    private javax.swing.JLabel Untiltxt5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration                   
}
